name: sync file
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  sync_file:
    name: sync_file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'settings.json'
          prefix: settings
          masked: false
          
      - name: Sync files with dst-repsotiory
        uses: waroad/sync-files@main
        with:
          git-author-email: ${{ secrets.USER_EMAIL }}
          git-author-name: ${{ secrets.USER_NAME }}
          sync-repository: Azure/azure-sdk
          allow-files-pattern: ${{ env.settings_path }}
          sync-branch-name: ${{ env.settings_branch }}
      - name: convert to po
        run : |
              pip install mdpo
              md2po md ./docs/policies/README-EXAMPLE.md -q -s -p ./docs/policies/ko.po
  
