name: sync file
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  job_1:
    name: sync file from orgin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
      - name: format json
        run: |
          python3 jsonFormating.py
          git add . 
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "format json"
          git push
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'settings_modified.json'
          prefix: settings
          masked: false
          
      - name: Sync files with dst-repsotiory
        uses: waroad/sync-files@main
        with:
          git-author-email: ${{ secrets.USER_EMAIL }}
          git-author-name: ${{ secrets.USER_NAME }}
          sync-repository: Azure/azure-sdk
          allow-files-pattern: ${{ env.settings_path_sum_sync }}
          sync-branch-name: ${{ env.settings_branch }}
          result-branch-name: main

