name: test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
      - name: Sync files with dst-repsotiory!
        uses: denis-tingaikin/sync-files@main
        with:
          git-author-email: 'waroad@knu.ac.kr'
          git-author-name: 'waroad'
          sync-repository: waroad/dummy-source-repo
          allow-files-pattern: '^data2.txt|^dd/rrr.md|^data.txt'
          sync-branch-name: 'master'
