name: sync file
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
          
      - name: Sync files with dst-repsotiory!
        uses: waroad/sync-files@main
        with:
          git-author-email: ${{ secrets.USER_EMAIL }}
          git-author-name: ${{ secrets.USER_NAME }}
          sync-repository: Azure/azure-sdk
          allow-files-pattern: '^docs/policies/README-EXAMPLE.md|^docs/policies/support.md'
          sync-branch-name: 'main'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          add-paths: |
            docs/policies/README-EXAMPLE.md
            docs/policies/support.md
          branch: sync/waroad/test1234
          
          
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'settings.json'
          prefix: settings
          masked: false
      - name: Show 2
        run: echo "The time was ${{ env.settings_path }}"
      - name: show 3
        run: for f in $settings_path; do echo f; done
      
