name: test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
      - name: Sync files with dst-repsotiory!
        uses: waroad/sync-files@main
        with:
          git-author-email: 'waroad@knu.ac.kr'
          git-author-name: 'waroad'
          sync-repository: Azure/azure-sdk
          allow-files-pattern: 'README.md'
          sync-branch-name: 'main'
