name: test
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
      - name: Sync files with dst-repsotiory!
        uses: waroad/sync-files@main
        with:
          git-author-email: 'waroad@knu.ac.kr'
          git-author-name: 'waroad'
          sync-repository: Azure/azure-sdk
          allow-files-pattern: '^docs/policies/README-EXAMPLE.md|^docs/policies/support.md'
          sync-branch-name: 'main'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          add-paths: |
            docs/policies/README-EXAMPLE.md
            docs/policies/support.md
          branch: sync/waroad/test1234
