name: make po
on:
  workflow_dispatch:
#   push:
jobs:
  job_1:
    name: make po file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: convert to po
        run : |
          mkdir -p po
          pip install mdpo
          md2po md ./docs/policies/README-EXAMPLE.md ./docs/policies/support.md -q -s -p ./subdir1/ko.po
      - name: Commit report
        run: |
          git add ./po
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "Automated report"
          git push
