name: move directory
on:
  push:
    branches:    
      - 'main'
    paths:
      - 'docs/**'
jobs:
    job_1: 
      name: move synced files to the desired directory
      runs-on: ubuntu-latest
      steps:
      - name: move synced files to the desired directory
        run: |
          mv docs/ mdpo/
          git add .
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "move synced files to the desired directory"
          git push
