name: remote pull request
on:
  workflow_dispatch:
jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "dir/fileName.txt"
          FILE_DATA: "file content"
