name: remote pull request
on:
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run : |
              mkdir subdir1
              pip install mdpo
              md2po md ./docs/policies/README-EXAMPLE.md -q -s -p ./subdir1/ko.po
      - name: Commit report
        run: |
          git add
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "Automated report"
          git push
