name: remote pull request
on:
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: waroad/test1234
          branch: sync/waroad/test1234
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: sync/waroad/test1234
